IMAGE_NAME = "freebsd/FreeBSD-14.1-RELEASE"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 1024
        vbox.cpus = 1
    end

    config.vm.define "fbsd14" do |fbsd|
        fbsd.vm.box = IMAGE_NAME
        fbsd.vm.network "forwarded_port", guest: 22, host: 2201, host_ip: "127.0.0.1"
        fbsd.vm.hostname = "fbsd14"
	config.vm.box_version = "2024.05.31"
	config.disksize.size = '20GB'
    end
end