IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = IMAGE_NAME
        ubuntu.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"
	ubuntu.vm.network "forwarded_port", guest: 80, host: 8002, host_ip: "127.0.0.1"
        ubuntu.vm.hostname = "ubuntu"
    end

    config.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys

    SHELL

    config.vm.provision "file", source: "pre-install-docker.yml", destination: "~/"

    config.vm.provision "shell", inline: <<-SHELL
	sudo apt update
	sudo apt install -y ansible net-tools git
	ansible-playbook pre-install-docker.yml
	git clone https://github.com/zabbix/zabbix-docker
	cd zabbix-docker
	sudo docker compose -f ./docker-compose_v3_ubuntu_pgsql_latest.yaml up -d

    SHELL







end